[[main]]
  name = "Podpora"
  identifier = "support"
  weight = 40
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  name = "Repositář"
  identifier = "repository"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  weight = 1
[[main]]
  name = "Diskuze"
  identifier = "discussions"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/discussions/new"
  weight = 2
[[main]]
  name = "Zlepšení vlastností"
  identifier = "feature-request"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=feature_request.md"
  weight = 3
[[main]]
  parent = "support"
  weight = 4
  [main.params]
    divider = true

[[footer]]
  name = "Podpora"
  identifier = "support"
  weight = 1
[[footer]]
  name = "Repositář"
  identifier = "repository"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  weight = 1
  pre = '<i class="fab fa-fw fa-github"></i>'
[[footer]]
  name = "Diskuze"
  identifier = "discussions"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/discussions/new"
  weight = 2
  pre = '<i class="fas fa-fw fa-comments"></i>'
[[footer]]
  name = "Zlepšení vlastností"
  identifier = "feature-request"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=feature_request.md"
  weight = 3
[[footer]]
  name = "Hlášení chyb"
  identifier = "bug-report"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=bug_report.md"
  weight = 4

[[footer]]
  name = "Dokumentace"
  identifier = "docs"
  weight = 2

[[footer]]
  name = "Vlastnosti"
  identifier = "features"
  weight = 3

[[footer]]
  identifier = "demo"
  name = "Demo"
  weight = 4
[[footer]]
  identifier = "demo-netlify"
  parent = "demo"
  name = "Netlify"
  weight = 1
  url = "https://hbs.razonyang.com"
[[footer]]
  identifier = "demo-china"
  parent = "demo"
  name = "China"
  weight = 2
  url = "https://hbs-cn.razonyang.com"
